version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_student_hub
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_hub_db
      MYSQL_USER: student_hub
      MYSQL_PASSWORD: student_hub_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: